"""
Report Generator for Company Research

Generates markdown and HTML reports
"""

from datetime import datetime


class ReportGenerator:
    """Generate comprehensive research reports"""

    def generate_markdown(self, company_name: str, collected_data: dict,
                         scores: dict, india_fit: dict) -> str:
        """
        Generate markdown report

        Args:
            company_name: Company name
            collected_data: All collected data
            scores: Overall scores from OverallScorer
            india_fit: India fit scores from IndiaFitScorer

        Returns:
            str: Markdown report
        """
        overall_score = scores.get('overall_score', 0)
        recommendation = scores.get('recommendation', 'insufficient_data')

        # Build report
        report = f"""# Company Research: {company_name}

**Generated**: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

---

## 🎯 Quick Recommendation

**Overall Score**: {overall_score}/100 {self._get_stars(overall_score)}

**India Fit**: {india_fit.get('india_fit_score', 0)}/100 🇮🇳

**Recommendation**: {self._format_recommendation(recommendation)}

---

## 📊 Score Breakdown

"""

        # Component scores
        if scores.get('company_health_score'):
            report += f"### Company Health: {scores['company_health_score']:.0f}/100\n"
            report += self._generate_bar(scores['company_health_score']) + "\n\n"

        if scores.get('employee_sentiment_score'):
            report += f"### Employee Sentiment: {scores['employee_sentiment_score']:.0f}/100\n"
            report += self._generate_bar(scores['employee_sentiment_score']) + "\n\n"

        if scores.get('growth_trajectory_score'):
            report += f"### Growth Trajectory: {scores['growth_trajectory_score']:.0f}/100\n"
            report += self._generate_bar(scores['growth_trajectory_score']) + "\n\n"

        if scores.get('compensation_score'):
            report += f"### Compensation: {scores['compensation_score']:.0f}/100\n"
            report += self._generate_bar(scores['compensation_score']) + "\n\n"

        report += "---\n\n"

        # India Fit Details
        report += f"""## 🇮🇳 India Fit Analysis

**Overall India Fit**: {india_fit.get('india_fit_score', 0)}/100

{india_fit.get('india_recommendation', 'No data')}

### Components:
- **Brand Awareness**: {india_fit.get('brand_awareness', 0):.0f}/100
- **Market Presence**: {india_fit.get('market_presence', 0):.0f}/100
- **Growth in India**: {india_fit.get('growth_in_india', 0):.0f}/100

---

"""

        # Detailed Data Sections
        report += self._generate_trends_section(collected_data.get('google_trends', {}))
        report += self._generate_glassdoor_section(collected_data.get('glassdoor', {}))
        report += self._generate_stock_section(collected_data.get('stock_market', {}))

        # Footer
        report += f"""
---

## 📄 Report Metadata

- **Confidence**: {scores.get('confidence', 0):.0%} (based on data availability)
- **Data Sources Used**: {self._get_sources_used(collected_data)}
- **Generated At**: {datetime.now().isoformat()}

---

*Generated by Auto Job Application - Company Research Module*
"""

        return report

    def _generate_trends_section(self, trends_result: dict) -> str:
        """Generate Google Trends section"""
        if not trends_result.get('success'):
            return "## 📈 Google Trends\n\n*Data unavailable*\n\n"

        data = trends_result.get('data', {})

        section = f"""## 📈 Google Trends Analysis

### Search Interest
- **Global Average**: {data.get('global_interest_avg', 0):.1f}/100
- **India Average**: {data.get('india_interest_avg', 0):.1f}/100
- **Trend Direction**: {data.get('trend_direction', 'Unknown').upper()}

"""

        # Regional breakdown
        regions = data.get('india_regions', {})
        if regions:
            section += "### Top Regions in India:\n"
            sorted_regions = sorted(regions.items(), key=lambda x: x[1], reverse=True)[:5]
            for region, score in sorted_regions:
                section += f"- **{region}**: {score}/100\n"

        section += "\n---\n\n"
        return section

    def _generate_glassdoor_section(self, glassdoor_result: dict) -> str:
        """Generate Glassdoor section"""
        if not glassdoor_result.get('success'):
            return "## 💼 Glassdoor (Employee Sentiment)\n\n*Data unavailable or scraping failed*\n\n"

        data = glassdoor_result.get('data', {})

        rating = data.get('overall_rating')
        if rating is None:
            return "## 💼 Glassdoor (Employee Sentiment)\n\n*No rating data available*\n\n"

        section = f"""## 💼 Glassdoor (Employee Sentiment)

### Overall Metrics
- **Overall Rating**: {rating}/5.0 ⭐
"""

        if data.get('ceo_approval'):
            section += f"- **CEO Approval**: {data['ceo_approval']}%\n"

        if data.get('recommend_to_friend'):
            section += f"- **Recommend to Friend**: {data['recommend_to_friend']}%\n"

        if data.get('review_count'):
            section += f"- **Total Reviews**: {data['review_count']:,}\n"

        section += "\n---\n\n"
        return section

    def _generate_stock_section(self, stock_result: dict) -> str:
        """Generate stock data section"""
        if not stock_result.get('success'):
            return "## 📊 Stock Performance\n\n*Data unavailable*\n\n"

        data = stock_result.get('data', {})

        if data.get('status') == 'private_company':
            return "## 📊 Stock Performance\n\n*Private company - no public stock data*\n\n"

        section = f"""## 📊 Stock Performance

**Ticker**: {data.get('ticker', 'N/A')}

### Current Metrics
- **Current Price**: ${data.get('current_price', 'N/A')}
- **Market Cap**: ${data.get('market_cap', 0):,.0f}
"""

        if data.get('pe_ratio'):
            section += f"- **P/E Ratio**: {data['pe_ratio']:.2f}\n"

        section += "\n### Performance\n"

        if data.get('performance_1mo'):
            section += f"- **1 Month**: {data['performance_1mo']:+.2f}%\n"

        if data.get('performance_3mo'):
            section += f"- **3 Months**: {data['performance_3mo']:+.2f}%\n"

        if data.get('performance_1yr'):
            section += f"- **1 Year**: {data['performance_1yr']:+.2f}%\n"

        section += "\n---\n\n"
        return section

    def _get_stars(self, score: float) -> str:
        """Convert score to stars"""
        if score >= 85:
            return "⭐⭐⭐⭐⭐"
        elif score >= 70:
            return "⭐⭐⭐⭐"
        elif score >= 55:
            return "⭐⭐⭐"
        elif score >= 40:
            return "⭐⭐"
        else:
            return "⭐"

    def _format_recommendation(self, recommendation: str) -> str:
        """Format recommendation with emoji"""
        formats = {
            'highly_recommended': '✅ **HIGHLY RECOMMENDED**',
            'recommended': '✅ **RECOMMENDED**',
            'moderate': '⚠️ **MODERATE** - Consider carefully',
            'caution': '⚠️ **CAUTION** - Significant concerns',
            'not_recommended': '❌ **NOT RECOMMENDED**',
            'insufficient_data': '❓ **INSUFFICIENT DATA**'
        }
        return formats.get(recommendation, recommendation.upper())

    def _generate_bar(self, score: float) -> str:
        """Generate ASCII bar chart"""
        filled = int(score / 10)
        empty = 10 - filled
        return '`' + '█' * filled + '░' * empty + '`'

    def _get_sources_used(self, collected_data: dict) -> str:
        """List successfully collected sources"""
        sources = []
        for source, result in collected_data.items():
            if result.get('success'):
                sources.append(source.replace('_', ' ').title())

        return ', '.join(sources) if sources else 'None'
